# PHP Quality Container - 
#
#
version: 2.1

executors:
  phpqc:
    docker:
      - image: ghcr.io/rschoonheim/phpqc:release
jobs:
  rector-php:
    executor: phpqc
    steps:
      - add_ssh_keys:
          fingerprints:
            - "30:5d:f1:8e:66:fb:9c:2c:c0:f1:b8:15:39:a4:d8:e9"
      - checkout
      - run: "rector"
      - run: "git-commit"
  code-style:
    executor: phpqc
    steps:
      - add_ssh_keys:
          fingerprints:
            - "30:5d:f1:8e:66:fb:9c:2c:c0:f1:b8:15:39:a4:d8:e9"
      - checkout
      - run: "pint"
      - run: "git-commit"
workflows:
  development:
    jobs:
      - rector-php:
          filters:
            branches:
              ignore: master
      - code-style:
          requires: 
            - rector-php
          filters:
            branches:
              ignore: master
    
    