# PHP Quality Container - 
#
#
version: 2.1

executors:
  phpqc:
    docker:
      - image: ghcr.io/rschoonheim/phpqc:latest

jobs:
  code-style:
    executor: phpqc
    steps:
      - add_ssh_keys
      - checkout
      - run: "pint"
      - run:
          name: Commit to GitHub
          command: |
            git config user.email "phpqc@circleci.com"
            git config user.name "CircleCI Job"
            git checkout master
            git commit --allow-empty -am "Automatic commit from CircleCI [skip ci]"
            git push origin master


workflows:
  development:
    jobs:
      - code-style:
        filters:
          branches:
            ignore: master
    
    